services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports: ["6379:6379"]
  backend:
    build: ./backend
    depends_on: [redis]
    env_file:
      - ./backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CHROMA_DIR=/data/chroma
    volumes:
      - ./backend:/app
      - ./data/chroma:/data/chroma
    ports: ["8000:8000"]
    command: uvicorn app:app --host 0.0.0.0 --port 8000
  frontend:
    build: ./frontend
    depends_on: [backend]
    environment:
      - API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    ports: ["8501:8501"]
    command: streamlit run /app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
